#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# local ruby gem
export PATH="/usr/local/opt/ruby/bin:$PATH"
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

# nvm
#   export NVM_DIR="$HOME/.nvm"
#   . "/usr/local/opt/nvm/nvm.sh"

# android-sdk
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"

# fastlane
export PATH=$HOME/.fastlane/bin:$PATH

# gitignore
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# flutter
# export PATH="$PATH:`pwd`/flutter/bin"

export GPG_TTY=$(tty)

# openssl
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
export PATH="/usr/local/opt/node@10/bin:$PATH"

# alias for rmtrash
alias trash="rmtrash"
alias del="rmtrash"